In [2]:
import pandas as pd
df = pd.read_csv('../data/finetuning_datasets/train_mcq_pairs_for_dpo.csv')
df.head()

,id,chosen,rejected,chosen_source,rejected_source
0,OIC-070-02-B,Question: Quelle est la prévalence des trouble...,Question: Quelle est la prévalence des trouble...,llama3_1_8b,openbiollm_8b
1,OIC-245-22-B,Question: Quelle est l'origine de l'insuffisan...,Question: Selon l'étiologie de l'insuffisance ...,openbiollm_8b,llama3_1_8b
2,OIC-227-08-A,Question: Quel est le stade ultime de l'insuff...,Question: Quelles sont les caractéristiques pr...,llama3_1_8b,openbiollm_8b
3,OIC-233-12-B,Question: Quel est le traitement médical indiq...,Question: Le traitement médical de l'insuffisa...,llama3_1_8b,openbiollm_8b
4,OIC-347-09-A,Question: Quels sont les éléments de gravité e...,Question: Quels sont les éléments de gravité e...,openbiollm_8b,llama3_1_8b

In [3]:
df.columns

Index(['id', 'chosen', 'rejected', 'chosen_source', 'rejected_source'], dtype='object')

In [4]:
chosen_part   = (df[['id', 'chosen', 'chosen_source']]
                 .rename(columns={'chosen': 'completion',
                                  'chosen_source': 'source'})
                 .assign(label=True))

rejected_part = (df[['id', 'rejected', 'rejected_source']]
                 .rename(columns={'rejected': 'completion',
                                  'rejected_source': 'source'})
                 .assign(label=False))

# combine and reorder columns ---------------------------------------------
new_df = (pd.concat([chosen_part, rejected_part], ignore_index=True)
            [['id', 'completion', 'label', 'source']])

new_df.head()

,id,completion,label,source
0,OIC-070-02-B,Question: Quelle est la prévalence des trouble...,True,llama3_1_8b
1,OIC-245-22-B,Question: Quelle est l'origine de l'insuffisan...,True,openbiollm_8b
2,OIC-227-08-A,Question: Quel est le stade ultime de l'insuff...,True,llama3_1_8b
3,OIC-233-12-B,Question: Quel est le traitement médical indiq...,True,llama3_1_8b
4,OIC-347-09-A,Question: Quels sont les éléments de gravité e...,True,openbiollm_8b

In [5]:
len(new_df)

1520

In [6]:
new_df = new_df.drop_duplicates(subset=['completion'], keep='first')

In [7]:
len(new_df)

1520

In [8]:
new_df = new_df.sample(frac=1).reset_index(drop=True)

In [9]:
len(new_df)

1520

In [10]:
new_df.to_csv('../data/finetuning_datasets/train_mcq_pairs_for_kto.csv', index=False)